# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Run hourly
    #- cron: '0 0,4,8,12,16,20 * * *'  # Run at specific hours (UTC)

name: schedule_posts

jobs:
  schedule_posts:
    timeout-minutes: 20    # Just in case
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RTOOT_DEFAULT_TOKEN: ${{ secrets.RTOOT_TOKEN }} # Your secret here
      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'

      - name: Install system dependencies
        run: sudo apt install libcurl4-openssl-dev

      - uses: r-lib/actions/setup-renv@v2

      - name: Check for scheduled posts
        run: Rscript schedule_posts.R
